Revert "Allow 5 hotseat icons in DISABLE_ALL_APPS mode."
This reverts commit f4ed1be4ef22c87b002c3bca90d130eb77fe5535.

This broke the build: 
packages/apps/Launcher3/src/com/android/launcher3/LauncherProvider.java:292: cannot find symbol
symbol  : variable default_workspace_no_all_apps
location: class com.android.launcher3.R.xml
            return R.xml.default_workspace_no_all_apps;

Change-Id: I40e80494f06f08de3d827c6816075ac4d269ea6a